version: '3'
services:
  mysql-database:
    image: mysql
    container_name: "mysql-database"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "devrep_projet1"
      MYSQL_USER: "devrep"
      MYSQL_PASSWORD: "devrep"

    networks:
      network-backend:

  frontend:
    build:
      dockerfile: "./frontend.dockerfile"
    container_name: "frontend"
    environment:
      PORT: "3000"
    ports:
      - "3000:3000"

    networks:
      network-backend:

  backend:
    build:
      dockerfile: "./backend.dockerfile"
    container_name: "backend"
    depends_on:
      - mysql-database
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql-database:3306/devrep_projet1?allowPublicKeyRetrieval=TRUE&useSSL=false",
        "spring.datasource.username" : "devrep",
        "spring.datasource.password" : "devrep",
        "app.security.jwt.keystore-location" : "keys/keystore.jks",
        "app.security.jwt.keystore-password" : "password",
        "app.security.jwt.key-alias" : "jwtsigning",
        "app.security.jwt.private-key-passphrase" : "password"
      }'

    ports:
      - "8080:8080"

    networks:
      network-backend:

networks:
    network-backend: